---
title: Marginal effect-filtered SFA GWIS for cardiometabolic traits
output: html_document
---

```{r setup, include=F}
knitr::opts_chunk$set(echo=F, cache.path="../cache/sfa_gwis_gwastools/",
                      fig.path="../output/figures/sfa_gwis_gwastools/")
suppressMessages(silent <- lapply(
  c("knitr", "tidyverse", "cowplot", "doParallel", "kableExtra",
    "glmnet", "broom", "GWASTools", "SNPRelate"), library, character.only=T))
```

```{r helpers}
INT <- function(x) qnorm((rank(x, na.last="keep") - 0.5) / sum(!is.na(x)))

winsorize <- function(x, num_SDs=5) {
  bounds <- mean(x, na.rm=T) + num_SDs * c(-1, 1) * sd(x, na.rm=T)
  case_when(x < bounds[1] ~ bounds[1],
            x > bounds[2] ~ bounds[2],
            TRUE ~ x)
}

make_qqplot <- function(p_vec, plotTitle="Title") {
  p_vec <- p_vec[!is.na(p_vec)]
  qqplot(-log10(1:length(p_vec) / length(p_vec)), -log10(p_vec), pch=".", 
         main=plotTitle, xlab="Expected (-logP)", ylab="Observed (-logP)")
  abline(0, 1, col="red")
}

gControl <- function(pVals) {
  # See van Iterson 2017 methods and/or Lehne 2015 code for details on genomic control for EWAS
  # Below is modeled after Lehne 2015
  lambda <- median(qchisq(pVals, df=1, lower.tail=F), na.rm=T) / qchisq(0.5, df=1)
  round(lambda, 2)
}
```

```{r gwis-funcs}
bim_to_SnADF <- function(bfile) {
  bim_df <- read_tsv(paste0(bfile, ".bim"), 
                     col_names=c("chromosome", "rsID", "cm", 
                                 "position", "A1", "A2")) %>%
    mutate(snpID=1:nrow(.)) %>%
    mutate_at(vars(chromosome, position), as.integer)
  SnpAnnotationDataFrame(data.frame(bim_df, stringsAsFactors=F))
}

fam_to_ScADF <- function(bfile) {
  phenos <- read_delim("../data/processed/gen3/whi_white_gwas_phenos.txt", 
                       delim=" ") %>%
    mutate(ldl=ifelse(lipid_med, ldl / 0.75, ldl),
           glu=ifelse(dm_med, glu / 0.75, glu),
           sbp=ifelse(ht_med, sbp + 15, sbp))
  fam_df <- read_delim(paste0(bfile, ".fam"), 
                       delim=" ", col_names=c("FID", "IID", "father", "mother", 
                                              "sex", "pheno")) %>%
    left_join(phenos, by=c("IID")) %>%
    mutate(scanID=IID)
  ScanAnnotationDataFrame(data.frame(fam_df, stringsAsFactors=F))
}

make_gds <- function(bfile, gds_name, summary=F) {
  snpgdsBED2GDS(paste0(bfile, ".bed"),
                paste0(bfile, ".fam"),
                paste0(bfile, ".bim"),
                gds_name,
                cvt.snpid="int")
  if (summary) snpgdsSummary(gds_name)
}

run_gwis_chunk <- function(genoData, outcome, covars, ivar, start, stop, robust=F) {
  assocRegression(
    genoData,
    outcome=outcome,
    model.type="linear",
    covar=covars,
    ivar=ivar,
    robust=robust,
    snpStart=start,
    snpEnd=stop)
}

covar_sets <- list(
  fat_carbEx=c("age", "fat", "pro", "alc", "tot_cal", paste0("PC", 1:5)),
  sfa_carbEx=c("age", "sfa", "mufa", "pufa", "pro", "alc", "tot_cal", 
               paste0("PC", 1:5))
)

interaction_vars <- list(
  fat_carbEx="fat",
  sfa_carbEx="sfa"
)

outcome_transforms <- list(
  bmi="logBMI",
  # hsCRP="logHSCRP",
  tg="logTG",
  glu="logGLU",
  ldl="ldl",
  sbp="logSBP"
)

run_gwis <- function(outcome, dv, genoset="suggestive", robust=T) {
    covars <- covar_sets[[dv]]
    ivar <- interaction_vars[[dv]]
    outcome_transform <- outcome_transforms[[outcome]]
    bfile <- paste0("../data/processed/whi_subsets/whi_", 
                    outcome, "_", genoset)
    
    snpAnnot <- bim_to_SnADF(bfile)
    scanAnnot <- fam_to_ScADF(bfile)
    gds_name <- paste0(bfile, ".gds")
    make_gds(bfile, gds_name)
    gds <- GdsGenotypeReader(openfn.gds(gds_name, allow.fork=T))
    genoData <- GenotypeData(gds, snpAnnot=snpAnnot, scanAnnot=scanAnnot)
    
    num_cores <- 8
    chunks <- as.integer(cut(1:nsnp(genoData), num_cores))
    cl <- makeForkCluster(num_cores)
    registerDoParallel(cl)
    res <- foreach(idx=unique(chunks), .combine=rbind, 
                       .packages="GWASTools") %dopar%
      run_gwis_chunk(genoData, outcome_transform, covars, ivar, 
                     min(which(chunks == idx)), max(which(chunks == idx)), 
                     robust=robust)
    stopCluster(cl)
    
    close(gds)
    
    res
}
```

```{r fat-carbEx-suggestive, cache=1}
fat_carbEx_res <- lapply(names(outcome_transforms), function(rf) {
  run_gwis(rf, "fat_carbEx")
})
```

```{r sfa-carbEx-suggestive, cache=1}
sfa_carbEx_res <- lapply(names(outcome_transforms), function(rf) {
  run_gwis(rf, "sfa_carbEx")
})
```

```{r fat-carbEx-nominal, cache=1}
fat_carbEx_res_nom <- lapply(names(outcome_transforms), function(rf) {
  run_gwis(rf, "fat_carbEx", "0.01")
})
```

```{r sfa-carbEx-nominal, cache=1}
sfa_carbEx_res_nom <- lapply(names(outcome_transforms), function(rf) {
  run_gwis(rf, "sfa_carbEx", "0.01")
})
```

```{r show-results}
top_hits <- function(res) {
  res %>%
    filter(MAF >= 0.01) %>%
    mutate(fdr=p.adjust(GxE.pval, method="BH")) %>%
    select(snpID, MAF, GxE.pval, Joint.pval, fdr) %>%
    arrange(fdr) %>%
    slice(1:10)
}

names(fat_carbEx_res) <- names(outcome_transforms)
lapply(names(fat_carbEx_res), function(x) {
  make_qqplot(fat_carbEx_res[[x]]$GxE.pval, paste0("fat_", x))
})

names(sfa_carbEx_res) <- names(outcome_transforms)
lapply(names(sfa_carbEx_res), function(x) {
  make_qqplot(sfa_carbEx_res[[x]]$GxE.pval, paste0("sfa_", x))
})

names(fat_carbEx_res_nom) <- names(outcome_transforms)
lapply(names(fat_carbEx_res_nom), function(x) {
  make_qqplot(fat_carbEx_res_nom[[x]]$GxE.pval, paste0("fat_", x))
})

names(sfa_carbEx_res_nom) <- names(outcome_transforms)
lapply(names(sfa_carbEx_res_nom), function(x) {
  make_qqplot(sfa_carbEx_res_nom[[x]]$GxE.pval, paste0("sfa_", x))
})
```

```{r annotate-results}
annotate_sumstats <- function(ss, bfile, maf_filter=0.01) {
  anno <- bim_to_SnADF(bfile) %>%
    getAnnotation() %>%
    select(snpID, rsID, chromosome, position, A1, A2)
  ss %>%
    filter(MAF>maf_filter) %>%
    select(snpID, MAF, n, GxE.Est, GxE.SE, GxE.pval) %>%
    inner_join(anno, by="snpID") %>%
    select(SNP=rsID, CHR=chromosome, BP=position, A1, A2, MAF, N=n, 
           BETA=GxE.Est, SE=GxE.SE, P=GxE.pval)
}
```

```{r export-results}
# sfa_bmi_0.01_res <- annotate_sumstats(
#   sfa_carbEx_res_nom$bmi,
#   "../data/processed/whi_subsets/whi_bmi_0.01")
# write_tsv(sfa_bmi_0.01_res, "../data/processed/gen3/sfa_bmi/sfa_bmi_0.01.res_raw")
# write_tsv(sfa_bmi_0.01_res, "../data/processed/gen3/sfa_bmi/sfa_bmi_0.01.res")

silent <- lapply(names(sfa_carbEx_res), function(rf) {
  write_tsv(sfa_carbEx_res[[rf]], 
            paste0("../data/processed/gen3/sfa_", rf, "/sfa_", rf,
                   "_suggestive.res_raw"))
  res_anno <- annotate_sumstats(sfa_carbEx_res[[rf]],
                                paste0("../data/processed/whi_subsets/whi_",
                                       rf, "_suggestive"))
  write_tsv(res_anno, paste0("../data/processed/gen3/sfa_", rf, "/sfa_", rf,
                             "_suggestive.res"))
})

silent <- lapply(names(sfa_carbEx_res_nom), function(rf) {
  write_tsv(sfa_carbEx_res_nom[[rf]],
            paste0("../data/processed/gen3/sfa_", rf, "/sfa_", rf,
                   "_0.01.res_raw"))
  res_anno <- annotate_sumstats(sfa_carbEx_res_nom[[rf]],
                                paste0("../data/processed/whi_subsets/whi_",
                                       rf, "_0.01"))
  write_tsv(res_anno, paste0("../data/processed/gen3/sfa_", rf, "/sfa_", rf,
                             "_0.01.res"))
})

silent <- lapply(names(fat_carbEx_res), function(rf) {
  write_tsv(fat_carbEx_res[[rf]], 
            paste0("../data/processed/gen3/fat_", rf, "/fat_", rf,
                   "_suggestive.res_raw"))
  res_anno <- annotate_sumstats(fat_carbEx_res[[rf]],
                                paste0("../data/processed/whi_subsets/whi_",
                                       rf, "_suggestive"))
  write_tsv(res_anno, paste0("../data/processed/gen3/fat_", rf, "/fat_", rf,
                             "_suggestive.res"))
})

silent <- lapply(names(fat_carbEx_res_nom), function(rf) {
  write_tsv(fat_carbEx_res_nom[[rf]],
            paste0("../data/processed/gen3/fat_", rf, "/fat_", rf,
                   "_0.01.res_raw"))
  res_anno <- annotate_sumstats(fat_carbEx_res_nom[[rf]],
                                paste0("../data/processed/whi_subsets/whi_",
                                       rf, "_0.01"))
  write_tsv(res_anno, paste0("../data/processed/gen3/fat_", rf, "/fat_", rf,
                             "_0.01.res"))
})
```
